### ISSUE TITLE
Unlock Content Technologies (epic)

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#211]
* [x] D3
 * [x] React
 * [x] ThreeJS
 * [ ] React Three Fiber
 * [ ] [REGL](https://github.com/regl-project/regl)
 * [ ] Leva
 * [ ] Vue
 * [ ] Svelte
 * [x] TypeScript
 * [x] Observable Plot
 * [ ] Observable Runtime?
 * [ ] Mapbox (partnership?)
 * [ ] [DuckDB](https://duckdb.org/)
