### ISSUE TITLE
Burn List

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#367]
# April
 * [x] Debug why some vizzes have v3 flag while they are not v3
 * [x] Increase price to $12/mo on April 1st
 * [x] Decrease size limit on free plan
 * [x] Bring back viz page upgrade nudge

# Get Customers
 * [ ] Introduce weekly office hours to paid plan
 * [ ] Move export feature to paid plan

# Finishing Existing Features

 * [ ] QA JSON API format with Val Town data updating
 * [ ] Restore to previous version
 * [ ] API for reading/writing private vizzes - secured with API key
 * [ ] Comments: Notification when someone comments on your viz
 * [ ] Shift+Enter when typing a comment should not trigger run

# WPI Lecture Videos

 * [ ] Scatter Plot with Menus
 * [ ] Coral Reefs on a Globe
 * [ ] Underwater Cables on a Globe
 * [ ] Multi-Line + Bar Chart (in progress)

# Videos Beyond WPI

 * New approach: Data + Questions --> Sketch --> Build --> Iterate } Condensed into 1-hour "Episodes"

# Get & Engage Customers
 * [ ] #917
 * [ ] #918
 * [ ] #919
 * [ ] Paywalled export

# New Features

 * [ ] Persistent Configuration for Personal Data Apps
 * [ ] JSX in V3 Runtime
 * [ ] Orgs first pass
 * [ ] Analytics Events on Search Results Page
 * [ ] Feature teasing for AI Assist
 * [ ] Turn off `backfillRuntimeVersion` on April 2nd or 3rd
 * [ ] Don't reset `srcdoc` for client-originated build errors
 * [ ] Do reset `srcdoc` for server-originated build errors
 * [ ] Do reset `srcdoc` for server-originated runtime errors
 * [ ] Do reset `srcdoc` for client-originated runtime errors
 * [ ] Reset `srcdoc` when dependencies change
 * [ ] #212
 * [ ] Create VizHub Blog and link it to `vuzhub.com/blog`
 * [ ] Create VizHub Newsletter
 * [ ] Suggested Vizzes
 * [ ] #830
 * [ ] Track what search terms are searched
 * [ ] API for creating vizzes re: https://github.com/room302studio/coachartie/issues/28
 * [ ] #726
 * [x] #822
 * [ ] Comments: Notification when someone comments on a viz that you commented on
 * [ ] Comments: Notification when someone @-mentions you
 * [ ] Comments: Mentions
 * [ ] Comments: Edit a Comment
 * [ ] https://github.com/vizhub-core/vizhub-feedback/issues/764
 * [ ] Clear out README while forking
 * [ ] Post-login Redirects https://github.com/vizhub-core/vizhub3/issues/300
 * [ ] Limit AI assist not by authenticated user but rather by the plan of the viz owner (if EITHER auth'd user OR viz owner has Premium, enable AI Assist).
 * [ ] Unfurl profile page #660

# VZCode / RCOS

# Medium Term
 * [ ] Import from viz #63 - client-side fetching of newly imported vizzes - support dynamically added imports from other vizzes - [VizPage handleCacheMiss] - fetch the viz content from the server if not in SSR viz cache
 * [ ] Terms Page
 * [ ] Show vizzes as starred in previews
 * [ ] Export high resolution image (paid feature)
 * [ ] Star/unstar viz from a preview
 * [ ] Handle infinite loops - bring back recovery mode
 * [ ] Mutate config or data files from within viz code - enables things like Kanban viz
 * [ ] Implement viz viewer header redesign from new Figma
 * [ ] Forum should link back to main VizHub site
 * [ ] Runtime: Get CSS working when you add the import after page load
 * [ ] Congratulations message when upgrading to Pro plan
 * [ ] Import from JSON
 * [ ] Show toast when unauthenticated user attempts to star a viz

# Long Term
 * [ ] Disable presence broadcast if no edit permissions
 * [ ] Add menu in upper right corner of viz previews
 * [ ] Reduce database bill by caching thumbnails
 * [ ] Link to product pages in Landing page
 * [ ] Google Analytics on Forum
 * [ ] When opening a viz from the create-viz page, show a message like "Fork this viz to make changes"
 * [ ] Adopt visual language from designs around plan icons
 * [ ] Runtime: Optimize CSS hot reloading to NOT trigger a JS build
 * [ ] [Pinned Vizzes](https://github.com/vizhub-core/vizhub3/issues/57)
 * [ ] README - update rendered README on the client
 * [ ] Advanced Analytics (paid feature) - see views over time for your vizzes
 * [ ] Code functionalities for creating Organization Accounts
 * [ ] Implement Manage and Delete features for Organization Accounts
 * [ ] Build Profile Page for Organization Account
 * [ ] Develop context switching between Personal and Organization Accounts
 * [ ] Update Pricing Page to include the Professional tier
 * [ ] Code advanced Search Results for Organizations
 * [ ] Implement Search within an Organization feature
 * [ ] Create Landing Page for Org Owners & Admins
 * [ ] Unit test Organization Account creation
 * [ ] Integration test context switching functionality
 * [ ] End-to-end test the complete Professional tier experience
 * [ ] Implement Folders Section on the Profile Page
 * [ ] Develop Create Folder functionality
 * [ ] Code Manage and Delete options for Folders
 * [ ] Build Folder Page with view and path/breadcrumbs
 * [ ] Implement Manage Collaborators and Permissions feature
 * [ ] Enable Organize Vizzes in Folders feature
 * [ ] Code for Specifying Ordering within Folders
 * [ ] Develop Nested Folders capability
 * [ ] Integrate Search Results for Folders feature
 * [ ] Implement Search within a Folder functionality
 * [ ] Unit test Folders creation and management
 * [ ] Integration test Permissions and Collaborators management
 * [ ] End-to-end test Folders and Advanced Access Control features
 * [ ] Simulate Color Blindness
 * [ ] Perceptual Color Picker

**Comment by curran** [comment]
Launched woohoo!

# Pre-launch - 2023
 * [x] Create the Fork Modal with basic functionality.
 * [x] Setup development environment and repositories for VizHub v3.
 * [x] Develop Public Section of the Profile Page.
 * [x] Viz Page view first pass.
 * [x] Program the Viz Viewer components.
 * [x] Build out the Viz Editor interface.
 * [x] Merge all VZCode PRs
 * [x] Review & merge TypeScript Linter VZCode PR
 * [X] QA newly merged features
 * [x] Integrate latest VZCode
 * [x] Deploy new VZCode version
 * [X] Delete Viz: Add trash button UI
 * [x] Refactor VerifyVizAccess to accept multiple actions
 * [x] Delete Viz: Add delete confirmation modal UI
 * [x] Image Generation: Fetch images from app endpoint
 * [x] Image Generation: Create app endpoint that returns sample data
 * [x] Image Generation: Make the app endpoint invoke image generation
 * [x] Auto-commit on viz page view
 * [x] Image Generation: Store images
 * [x] Image Generation: Fetch images
 * [x] Image Generation: Resize images
 * [x] Delete Viz: Wire up the app to add the button and show the modal
 * [x] Delete Viz: Don't show delete viz button unless user has permissions to delete viz
 * [x] Delete Viz: Implement server-side deletion upon clicking through delete confirmation modal (make this "Trash" the viz internally)
 * [x] Trashed viz toast
 * [x] Deploy latest VZCode to beta
 * [x] Fix link to copy in Share modal
 * [x] Show "Copied" after clicking "copy" in Share modal
 * [x] [Linting is Too Aggressive](https://github.com/vizhub-core/vzcode/issues/363#top)
 * [x] Viz Editor - Recover from Runtime Errors
 * [x] Viz Editor - Don't run on each keystroke
 * [x] Permission denied - don't show link to fork when user not logged in
 * [X] Don't show more button if there's no more
 * [x] Import from viz #63 - first pass (server -side)
 * [x] Tests for `createVizCache`
 * [x] Import from viz #63 - pass viz cache to client so client builds work
 * [x] Import from viz #63 - hot reload when dependencies change - instantiate ShareDB docs for vizCacheContentSnapshots
 * [x] Import from viz - support thumbnail generation
 * [x] Surface UI kitchen sink page(s) for Sam
 * [x] Iterate monospace font in vizhub-ui
 * [x] Upgrade vzcode to latest vizhub-ui
 * [x] Cut a VZCode release
 * [x] Runtime: Get CSS working for local CSS imports - first pass
 * [x] Runtime: Get CSS working for imports from other vizzes - first pass
 * [x] Runtime: Get CSS working on page load
 * [x] Import from CSV #270 
 * [x] Runtime: Remove CSS when its import is removed
 * [x] Merge this PR https://github.com/vizhub-core/vizhub-ui/pull/9
 * [x] Cut a vizhub-ui release
 * [x] Style sidebar as bold monospace in VZCode
 * [x] Style tabs as bold monospace in VZCode
 * [x] https://github.com/vizhub-core/vizhub-ui/issues/10
 * [x] https://github.com/vizhub-core/vzcode/issues/392
 * [X] Add UI for custom URLs
 * [x] Dedupe image storage  https://github.com/vizhub-core/vizhub3/pull/new/dedupe-stored-images
 * [x] Nuke production DB for the last time
 * [x] Iterate mongodb collection names to remove "s"
 * [X] Re-migrate primordial viz (including upvotes)
 * [x] Fix crash when deleting index.html #439
 * [x] Disable editing of v2 vizzes
 * [x] QA https://github.com/vizhub-core/vizhub3/pull/445
 * [X] Iterate V3 Runtime: export const viz
 * [X] Iterate V3 Runtime: give container measurable dimension
 * [x] Re-migrate Primordial Viz
 * [x] Clean up console logs
 * [x] Nita Beta Testing Begins
 * [X] Make intro video 1
 * [X] Iterate auto-run to explicit run - CTRL+S - for V3 vizzes
 * [x] Fix empty commit authors #459
 * [x] Add comma formatter to forks count
 * [x] "More" button on Forks page
 * [x] Make private section of profile page working
 * [x] Stripe checkout different for monthly vs annual plans
 * [x] Change pricing page to say "Current" is pro, Free plan links to billing portal and says "Downgrade"
 * [x] Adopt Redis Pub Sub
 * [x] Adopt RedLock
 * [x] Deploy 2X server
 * [x] Reconnecting Websockets #455
 * [X] Viz editor - use Prettier config from V2
 * [X] Hide viz viewer if no index.js
 * [X] Remove pricing page link for now
 * [x] Profile Page Section: Shared with me #316
 * [x] Change page size from 50 to 100
 * [x] [Completions sometimes leave cursor on the left](https://github.com/vizhub-core/vzcode/issues/362)
 * [x] Share Modal: Manage Collaborators Section
 * [x] Get AI Assist Working Again
 * [X] Create Viz Page - first pass
 * [X] Deal with existing private vizzes on free plan
 * [X] Lock Down AI Assist - show modal when clicking AI icon on free plan
 * [X] Lock Down Collaborators - disable collaborators on free plan
 * [x] V3 export from client
 * [x] Disable private viz option for now (in Fork modal, and in Settings)
 * [x] Auto-commit service #308 
 * [x] Enable shared Vizzes section in the Profile Page.
 * [x] Implement Collaborators section in Share Modal.
 * [x] Launch V2 read-only archive to v2.vizhub.com
 * [x] Pricing Page First Pass.
 * [x] Integrate Stripe Checkout into the Upgrade Flow.
 * [x] Review Figma mockups for Premium tier specific features.
 * [x] Link Account Page to Stripe Billing Portal.
 * [x] Complete migration
 * [x] Code the Pricing Page with Free and Premium options (from new designs).
 * [x] Construct Private Section of the Profile Page.
 * [x] Implement visibility switching in Fork Modal for Private Vizzes.
 * [x] Program Settings Modal for Private Vizzes.
 * [X] Build AI-Assisted Coding start/stop UX, first pass.
 * [x] QA and refine AI-Assisted Coding start/stop UX.
 * [x] Launch V3 to vizhub.com

**Comment by curran** [comment]
# January 2024
 * [x] Get the forum posting working again
 * [x] Add unfurl image to home page
 * [x] Migration second pass (upvotes, collaborators, latest updates)
 * [x] Iterate padding around "More" button
 * [x] Lock down client-originated info ops and ops for all other entities
 * [X] Remove AI Assist data from Content
 * [X] Test Stripe flows for upgrade/downgrade
 * [X] Review entire system for broken features and disable all of them
 * [x] AI Assist - track analytics events
 * [X] Use new image URLs in unfurl meta
 * [X] Auto-commit on viz preview image request
 * [x] Google Analytics on App
 * [x] Set height
 * [x] Starring work #119 
 * [x] Iterate padding on Profile page so that it has more padding on large screens and less on small
 * [x] Iterate padding on home page
 * [x] Create V3 starter and record it
 * [x] Commit viz when loading thumbnail?
 * [x] Custom URLs: Extend data model: add `slug` to `Info` entity
 * [x] Custom URLs: Use `info.slug` to create links from `VizPreviews` - see https://github.com/Flet/github-slugger
 * [x] Custom URLs: Navigate to new URL when saving a change to the slug
 * [x] Custom URLs: Validate that the slug is not already taken
 * [x] Custom URLs: Get slugs working for import from viz feature
 * [x] Add padding to Explore and Forks page
 * [x] Compute popularity scores
 * [x] Sort by popular by default on home page
 * [x] My starred vizzes section
 * [x] Make intro video 2
 * [x] Don't allow multiple free trials
 * [x] Solve layout issue on profile page when number of vizzes is small e.g. 1
 * [x] Fix hover glitch with tooltip on AI assist button
 * [x] Fix VZCode URL Params Issues
 * [x] Follow trashed vizzes to populate `forkedFrom`
 * [x] Mark info as V3 runtime (or "Hot Viz") in `Info`
 * [x] Always collect credit card info
 * [x] Pricing page unfurl image & new copy
 * [x] Feature Page: AI Assist
 * [x] Link in Pricing page to Feature Page: AI Assist
 * [x] Pricing page mobile layout
 * [X] Fix btoa bug https://github.com/vizhub-core/vizhub3/issues/631
 * [x] New landing page
 * [x] Create Viz Page - second pass - index all examples from courses for easy access
 * [x] Fix svelte error when binding to dimensions
 * [X] Detect and report new size limit error code in the client UI
 * [X] Implement different size limits for different plans
 * [X] Introduce size limit on free plan (UI)
 * [x] Iterate landing page CTA copy "get started"
 * [x] Iterate landing page copy
 * [x] Logged in 'get started' goes to Create Page
 * [x] Footer

**Comment by curran** [comment]
# February
 * [x] Export Image
 * [x] Footer on multiple pages
 * [x] Add upgrade nudge banner on free user's public vizzes
 * [x] AI Assist - show loading spinner during generation
 * [x] Viz Editor - Show intercepted build errors in VZCode error space
 * [x] Show errors to user: `Unresolved import from vizId ${vizId}`
 * [x] Search First Pass
 * [x] Download PNG Feature
 * [x] Svelte Prettier
 * [x] Support forkedFrom page when using slug instead of id
 * [x] Disable Svelte warning for missing Prettier parser
 * [x] Fix comma format for forks count
 * [x] #75
 * [x] Search https://github.com/vizhub-core/vizhub3/issues/103
 * [x] AI Assist: Upgrade Nudge Modal
 * [x] Stargazers #124 - Add ability to see who starred your viz
 * [x] Iterate auto-run to explicit run - CTRL+S - for V2 vizzes
 * [x] Hide top bar when editor is open
 * [x] Faster CSV parsing https://chat.openai.com/c/2a84e0d7-9ca3-4f13-9488-b701eb8149ac
 * [x] Feature Page: Hot Reloading & Interactive Widgets
 * [x] AI Assist: Run Prettier After Generation https://github.com/vizhub-core/vzcode/issues/455
 * [x] Design - Make the AI Assist button pop out more (border, larger, different color maybe)
 * [x] Play button to run the code (with tooltip explaining Ctrl+S) https://github.com/vizhub-core/vzcode/issues/77
 * [x] Export runnable files via API
 * [x] https://github.com/vizhub-core/vzcode/issues/456
 * [x] Support slugs in JSON API
 * [x] https://github.com/vizhub-core/vizhub3/issues/777
 * [x] https://github.com/vizhub-core/vizhub3/issues/783
 * [x] Comments: Render Markdown
 * [x] Document JSON API
 * [x] Document Zip API
 * [x] Link in Pricing page to Feature Page: Hot Reloading & Interactive Widgets
 * [x] Feature Page: Private Vizzes
 * [x] Link in Pricing page to Feature Page: Private Vizzes
 * [x] Feature Page: Collaborators
 * [x] Link in Pricing page to Feature Page: Collaborators
 * [x] Viz Editor - Show intercepted runtime errors in VZCode error space
 * [X] API for writing vizzes - unsecured

**Comment by curran** [comment]
# March
 * [x] https://github.com/vizhub-core/vizhub-feedback/issues/766#issuecomment-1933866501
 * [x] Iterate Landing Page & Pricing Page Copy
 * [x] Move Landing Page back to home page
 * [x] Redirect to profile page from home page if authenticated
 * [x] Fix CSV encoding bug
 * [X] Start on notifications and API keys in entities and profile UI
 * [x] Vite + NPM Workspaces export including transitive dependencies
 * [x] API for writing vizzes - secured with API key
 * [x] API key management UI
 * [x] Start on revision history
 * [x] https://github.com/vizhub-core/vzcode/issues/426
 * [x] 18px font size for code editor and README copy
 * [x] Document Keyboard Shortcuts https://github.com/vizhub-core/vzcode/issues/228
 * [x] Resources tab (menu in the nav bar linking to documentation of features)
 * [x] #897 
 * [x] Viz Editor - Extensive QA to ensure it never crashes/stops building
