### ISSUE TITLE
[epic] Viz Page / Read-only

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#40]
* [x] Starter
 * [x] Header
 * [x] Fork Modal - part of [#37](https://github.com/vizhub-core/vizhub3/issues/37)
 * [x] Record analytics event for viz page view #89 
 * [x] title
 * [x] upvotes count (UI only)
 * [x]  upvotes count (read only, in viz page)
 * [x] DescriptionSection #91 
 * [x] Markdown rendering (static)
 * [x] license
 * [x] Runner (V2 Runtime) #88 
 * [x] #190
 * [x] V2 Export #61
 * [ ] full-screen mode (button, icon, functionality) #191
