### ISSUE TITLE
[epic] Viz Page / Editable

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#41]
* [x] VZCode Integration
 * [x] Upvotes count display in viz page (click to upvote, click again to un-upvote)
 * [ ] Show/hide header interaction
 * [ ] Store Show/hide header interaction state in URL
 * [ ] Share Modal
 * [ ] Settings Modal
 * [ ] Settings Modal / visibility switching #38
 * [x] V3 Runtime #64 
 * [ ] V3 Export #62
 * [ ] Import from Viz #63 
 * [ ] Manage Collaborators on Viz #59
