### ISSUE TITLE
Revision History (epic)

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#58]
* [x] Data model
 * [x] Use in interactors
 * [x] Migration
 * [x] UI for displaying revision history
 * [ ] UX for navigating revision history
 * [ ] UX for restoring a viz to a previous version
 * [ ] Link to specific version
 * [x] Thumbnails for each revision
 * [ ] Import from specific version
 * [ ] Solve diamond dependency problem
 * [ ] Embed specific version
 * [ ] Publish a specific version

**Comment by curran** [comment]
Closing in favor of 

https://github.com/vizhub-core/vizhub-feedback/issues/781
