### ISSUE TITLE
[Epic] V3 Export

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#62]
* [x] V3 Export to Vite / Vanilla
 * [ ] V3 Export to React
 * [ ] V3 Export to Vue
 * [ ] V3 Export to Svelte
