### ISSUE TITLE
Pro Plan (epic)

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#71]
* [ ] Unlisted vizzes #72 
 * [x] Upgrade flow #83 
 * [x] Stripe integration #84 
 * [x] Downgrade flow #85 
 * [ ] Private folders #67 
 * [ ] Unlimited private vizzes
 * [ ] Unlisted folders
 * [ ] Password protected vizzes
 * [ ] Password protected folders
 * [ ] Unlimited collaborators
 * [ ] User seats are defined as total collaborators on non-public content
 * [ ] Visualize total collaborators across account
 * [ ] Easily remove a specific collaborator from all vizzes and folders
 * [ ] Unlimited collaboration sessions with audio/video presence
 * [ ] Record collaboration sessions with audio/video presence
 * [ ] Live stream collaboration sessions with audio/video presence
