### ISSUE TITLE
[epic] Embedding

### ISSUE THREAD

**Issue by curran** [vizhub-studio/vizhub#75]
* [x] Implement embedded view `mode=embed`
 * [x] Expose a link to "pop out" the full screen viz
 * [x] Share Modal: Embed Section
 * [x] Embed UI in Share modal
 * [x] QA in Medium - it doesn't work and we'd have to pay $100/mo for Embedly
 * [x] Embed latest version of a viz with VizHub logo #76 
 * [x] Whitelabel embedding #77 
 * [x] Update Share Modal for White Label Embedding
 * [x] Add whitelabel option for paying customers only
 * [x] add feature listing in pricing page
 * [x] add feature listing in landing page
 * [x] create documentation page
